### PR TITLE
add Zero To Production In Rust book

### PR DESCRIPTION
**Pull request by JekRock**

### CODE REVIEW

**Comment by Wandalen** [comment]
Hello. 

image

There is no book available for free behind the link. It does not look like it is intended to be shared for free.

**Comment by JekRock** [comment]
That's correct.
README in this repository doesn't mention that there must be free resources only.

**Comment by Wandalen** [comment]
Perhaps I should mention it. But I am not sure where and how.

**Comment by JekRock** [comment]
Maybe something like that in README would work
> Curated collection of lists of useful **free** resources to learn Rust together.

**Pull request closed without merging**
